---
- name: Install Prometheus on CentOS 9 as root in /opt/prometheus
  hosts: web
  become: true

  vars:
    prometheus_version: "2.52.0"
    install_dir: /opt/prometheus
    prometheus_port: 9090

  tasks:
    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop:
        - "{{ install_dir }}"
        - "{{ install_dir }}/data"
        - "{{ install_dir }}/extract"

    - name: Download Prometheus tarball
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "{{ install_dir }}/prometheus.tar.gz"
        mode: "0644"

    - name: Extract Prometheus tarball to /opt/prometheus/extract
      unarchive:
        src: "{{ install_dir }}/prometheus.tar.gz"
        dest: "{{ install_dir }}/extract"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Move Prometheus binaries to /usr/local/bin
      copy:
        remote_src: yes
        src: "{{ install_dir }}/extract/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
      loop:
        - prometheus
        - promtool

    - name: Copy Prometheus config and console files to /opt/prometheus
      copy:
        remote_src: yes
        src: "{{ install_dir }}/extract/{{ item }}"
        dest: "{{ install_dir }}/{{ item }}"
      loop:
        - prometheus.yml
        - consoles
        - console_libraries

    - name: Create systemd service file for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          Group=root
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file={{ install_dir }}/prometheus.yml \
            --storage.tsdb.path={{ install_dir }}/data

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec

