name: Test Ansible Connection

on:
  workflow_dispatch:

jobs:
  test-ansible-connections:
    runs-on: [ ansible-master ]

    steps:
    
      - name: Test connections with ping module
        run: |
          ansible all --list-hosts -i /home/shruti/ansible/inventory.yaml  
      - name: Add SSH key
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            

            
      - name: Gather facts (more comprehensive test)
        run: |
        
          ansible all -m user -a "name=newbie state=present" -i /home/shruti/ansible/inventory.yaml  
          ansible all -m "id newbie" -i /home/shruti/ansible/inventory.yaml
