name: Test Ansible Connection

on:
  workflow_dispatch:

jobs:
  test-ansible-connections:
    runs-on: [ ansible-master ]

    steps:
    
      - name: Test connections with ping module
        run: |
          ansible all --list-hosts -i /home/shruti/ansible/inventory.yaml
        env:
         ANSIBLE_HOST_KEY_CHECKING: False
         ANSIBLE_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         HOST_IP1: ${{ secrets.HOST_IP1 }}
         HOST_IP2: ${{ secrets.HOST_IP2 }}

      - name: Add SSH key
        run: |
         mkdir -p ~/.ssh
         echo echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H ${{ secrets.HOST_IP1 }} >> ~/.ssh/known_hosts
         ssh-keyscan -H ${{ secrets.HOST_IP2 }} >> ~/.ssh/known_hosts
         
      - name: Gather facts and test user creation
        run: |
          ansible all -m ping -i /home/shruti/ansible/inventory.yaml
          ansible all -m user -a "name=newbie state=present" -i /home/shruti/ansible/inventory.yaml
          ansible all -m shell -a "id newbie" -i /home/shruti/ansible/inventory.yaml
