name: ENCRYPT
on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:
  

jobs:
  encrypt-playbook:
    runs-on: [ ansible-master ]  # Change this if you're not using a self-hosted runner

    
    steps:
      - uses: actions/checkout@v4

      - name: Execute Ansible Playbook
      
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |  
          ansible-vault encrypt playbook1-useradd.yaml 
