name: Deploy with Ansible

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ansible-master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Role
        run: |
          ansible-galaxy install -p /home/shruti/ansible/roles geerlingguy.nginx
      
      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          pwd
          cp /home/shruti/ansible/roles/geerlingguy.nginx/inventory .
          cp /home/shruti/ansible/roles/geerlingguy.nginx/ansible.cfg .
          ansible-playbook -i /home/shruti/ansible/inventory.yaml site.yaml site.yaml
